server:
  port: 8900
  servlet:
    context-path: /auth

spring:
  application:
    name: authenticationservice
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/eric?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: zhou123
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
    timeout: 3000

mybatis:
  mapper-locations: 'classpath:mybatis/mapping/**.xml'
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: eric.authentication.module.entity

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/