auth-server: http://127.0.0.1:8900/auth
security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: eric-api-gateway
      user-info-uri: ${auth-server}/user
      prefer-token-info: false
      #token-info-uri: ${auth-server}/oauth/check_token

server:
  port: 8888

spring:
  application:
    name: apigateway
    
zuul:
  routes:
    app1:
      path: /api-1/**
      serviceId: apperic1
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/