server:
  port: 8902

spring:
  application:
    name: apperic2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eric?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: zhou123
    driver: com.mysql.jdbc.Driver
  kafka:
    #============== kafka ===================
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 127.0.0.1:9092
    #============= provider =================
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #============= consumer =================
    consumer:
      #指定默认消费者group id
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

logging:
  level:
    root: INFO
    xiangxing: INFO